/**
 * RetroAchievements and speedrun.com console name/id maps.
 */

// =========================================
//          Console Mappings
// =========================================
export const RAConsole = {
  ARCADE: "Arcade",
  SNES: "SNES/Super Famicom",
  NES: "NES/Famicom",
  GAMEBOY: "Game Boy",
  GAMEBOYCOLOR: "Game Boy Color",
  GAMEBOYADVANCE: "Game Boy Advance",
  NINTENDO64: "Nintendo 64",
  GAMECUBE: "GameCube",
  NINTENDODS: "Nintendo DS",
  NINTENDODSI: "Nintendo DSi",
  ATARI2600: "Atari 2600",
  ATARI7800: "Atari 7800",
  ATARIJAGUAR: "Atari Jaguar",
  ATARIJAGUARCD: "Atari Jaguar CD",
  ATARILYNX: "Atari Lynx",
  PCENGINE: "PC Engine/TurboGrafx-16",
  PCENGINECD: "PC Engine CD/TurboGrafx-CD",
  MASTERSYSTEM: "Master System",
  GAMEGEAR: "Game Gear",
  MEGADRIVE: "Genesis/Mega Drive",
  SEGA32X: "32X",
  SEGACD: "Sega CD",
  SATURN: "Saturn",
  DREAMCAST: "Dreamcast",
  PS1: "PlayStation",
  PS2: "PlayStation 2",
  PSP: "PlayStation Portable",
  P3DO: "3DO Interactive Multiplayer",
  NEOGEOCD: "Neo Geo CD",
  NEOGEOPOCKET: "Neo Geo Pocket",
  POKEMINI: "Pokemon Mini",
  VIRTUALBOY: "Virtual Boy",
  SG1000: "SG-1000",
  COLECO: "ColecoVision",
  MSX: "MSX",
  WII: "Wii",
  WONDERSWAN: "WonderSwan",
  VECTREX: "Vectrex",
  NEC8800: "PC-8000/8800",
  APPLEII: "Apple II",
  PCFX: "PC-FX",
  ARDUBOY: "Arduboy",
  ARCADIA: "Arcadia 2001",
  FAIRCHILD: "Fairchild Channel F",
  MAGNAVOXODYSSEY2: "Magnavox Odyssey 2",
  INTELLIVISION: "Intellivision",
  INTERTONVC4000: "Interton VC 4000",
  MEGADUCK: "Mega Duck",
  WATARA: "Watara Supervision",
  ZEEBO: "Zeebo",
  AMSTRADCPC: "Amstrad CPC",
  UZEBOX: "Uzebox",
  WASM4: "WASM-4"
};

export const SRConsole = {
  PC: "8gej2n93",
  APPLEII: "w89ryw6l",
  ATARI2600: "o0644863",
  ARCADE: "vm9vn63k",
  NEC8800: "7g6mw8er",
  COLECOVISION: "wxeo8d6r",
  COMMODORE64: "gz9qox60",
  MSX: "jm950z6o",
  NES: "jm95z9ol",
  MSX2: "83exkk6l",
  MASTERSYSTEM: "83exwk6l",
  ATARI7800: "gde33gek",
  FAMICOMDISKSYSTEM: "mr6k409z",
  PCENGINE: "5negxk6y",
  MEGADRIVE: "mr6k0ezw",
  GAMEBOY: "n5683oev",
  NEOGEOAES: "mx6p4w63",
  GAMEGEAR: "w89r3w9l",
  SNES: "83exk6l5",
  PHILIPSCDI: "w89rjw6l",
  SEGACD: "31670d9q",
  PANASONIC3D0: "8gejmne3",
  NEOGEOCD: "kz9w7mep",
  PCFX: "p36n8568",
  PS1: "wxeod9rn",
  SEGA32X: "kz9wrn6p",
  SEGASATURN: "lq60l642",
  VIRTUALBOY: "7g6mk8er",
  NINTENDO64: "w89rwelk",
  GAMEBOYCOLOR: "gde3g9k1",
  NEOGEOPOCKETCOLOR: "7m6ydw6p",
  TURBOGRAFX16CD: "p36nlxe8",
  DREAMCAST: "v06d394z",
  WONDERSWAN: "vm9v8n63",
  PLAYSTATION2: "n5e17e27",
  WONDERSWANCOLOUR: "n568kz6v",
  GAMEBOYADVANCE: "3167d6q2",
  GAMECUBE: "4p9z06rn",
  POKÉMONMINI: "vm9vr1e3",
  NINTENDODS: "7g6m8erk",
  PLAYSTATIONPORTABLE: "5negk9y7",
  WII: "v06dk3e4",
  AMSTRADCPC: "5negykey"
};
